vocab: 5
iterations: 2
mini_batch_size: 10
word_embedding_dim: 10
image_embedding_dim: 10
model_weights: vgg16.npy
learning_rate: 0.2
load_model: False

log_path: logs

data_dir: data
image_dirs:
    - dog
    - cat
vocab:
    - dogword
    - catword